#! /usr/bin/env python

#Benedict homework Python II

#goal: write code to create a list of numbers and loop through the list, adding 1 to every number, and print those numbers

#make list of numbers
MyList = ()
MyList = (22,24,26,28,42,44,46,48)

#make for loop

for x in MyList:
	print(x+1)


#goal question 4: create dictionary and list with animals, print "big" if animal is over 20 grams and print "small" if animals is less than 20 grams

#make dictionary
Animal_Dict = {}
Animal_Dict["pika"] = 110
Animal_Dict["chickadee"] = 10
Animal_Dict["kangaroo"] = 28500
Animal_Dict["shrew"] = 15

#make list
AnimList = ()
AnimList = Animal_Dict.keys()

#else statements
for key in Animal_Dict:
	if Animal_Dict[key] > 20:
		print

for x in AnimList:
	if Animal_Dict[x] > 20:
		print("x, big")
	else:
		print("x, small")
